[workspace]
resolver = "3"
members = [
    "crates/*",
    "."
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
thiserror = "2.0"
syn = { version = "3.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
proc-macro-crate = "3"
const-default = "1.0.0"

macros = { path = "crates/macros" }
internal-macros = { path = "crates/internal-macros" }

[package]
name = "command"
version.workspace = true
edition.workspace = true

[dependencies]
macros.workspace = true
internal-macros.workspace = true
thiserror.workspace = true
const-default = { workspace = true, optional = true, features = ["derive"] }

[features]
const = ["macros/const", "dep:const-default"]

[[example]]
name = "basics"
path = "examples/basics.rs"

[[example]]
name = "const"
path = "examples/const.rs"
required-features = ["const"]

[[example]]
name = "context"
path = "examples/advanced.rs"
